// =========================================================================
// THEMES
// Each theme has:
//   - an id (matches profiles.theme)
//   - a human label
//   - a copy dictionary (UI strings that get flavored per theme)
//   - a set of CSS variable values applied to <body data-theme="...">
// CSS variable values live in styles/themes.css keyed off data-theme.
// =========================================================================

export type ThemeId = 'dnd' | 'alien' | 'horror' | 'marquee' | 'cozy' | 'space' | 'oldwest' | 'nineties' | 'underwater' | 'station' | 'neutral';

export type ThemeCopy = {
  appName: string;
  tasks: string;             // plural for nav + headers
  task: string;              // singular
  newTask: string;           // button: "Add Task"
  completeTask: string;      // button: "Mark Done"
  completedToast: (xp: number, gold: number) => string;
  tasksSubtitle: string;
  inventory: string;
  inventorySubtitle: string;
  searchInventory: string;
  depleted: string;
  lowStock: string;
  recipes: string;
  recipesSubtitle: string;
  allIngredientsPresent: string;
  missingIngredients: (n: number) => string;
  notifications: string;
  notificationsSubtitle: string;
  sendNotification: string;
  shopping: string;              // nav label for shopping list
  shoppingSubtitle: string;
  addToShopping: string;
  shoppingEmpty: string;
  aiSuggest: string;             // button: "What can I make?"
  aiSuggestSubtitle: string;
  aiThinking: string;
  storage: {                     // filter chip labels (all / fridge / freezer / pantry)
    all: string;
    fridge: string;
    freezer: string;
    pantry: string;
  };
  addToShoppingAction: string;   // short label for the in-kitchen "add to list" button
  xpLabel: string;           // e.g. "XP" or "SIGNAL"
  goldLabel: string;         // e.g. "GP" or "CREDITS" or "HONEY"
  levelLabel: string;
  todayLabel: string;
  filters: {
    all: string;
    mine: string;
    open: string;
    urgent: string;
    done: string;
  };
  tiers: { common: string; rare: string; epic: string; urgent: string };
  assignee: string;
  ornament: string;          // decorative divider character(s)
};

export const THEMES: Record<ThemeId, { id: ThemeId; label: string; copy: ThemeCopy }> = {
  neutral: {
    id: 'neutral',
    label: 'Neutral',
    copy: {
      appName: 'Household',
      tasks: 'Tasks',
      task: 'Task',
      newTask: 'Add Task',
      completeTask: 'Mark Done',
      completedToast: (xp, gold) => `Done · +${xp} XP · +${gold} coin`,
      tasksSubtitle: 'what needs doing',
      inventory: 'Kitchen',
      inventorySubtitle: 'what\'s in the house',
      searchInventory: 'Search items…',
      depleted: 'Out',
      lowStock: 'Low',
      recipes: 'Recipes',
      recipesSubtitle: 'what we can cook',
      allIngredientsPresent: 'All ingredients on hand',
      missingIngredients: (n) => `${n} ingredient${n === 1 ? '' : 's'} missing`,
      notifications: 'Alerts',
      notificationsSubtitle: 'news from the house',
      sendNotification: 'Send Alert',
      shopping: 'Shopping',
      shoppingSubtitle: 'what we need to buy',
      addToShopping: 'Add to list',
      shoppingEmpty: 'Nothing on the list.',
      aiSuggest: 'What can I make?',
      aiSuggestSubtitle: 'based on what you have',
      aiThinking: 'Thinking…',
      storage: { all: 'All', fridge: 'Fridge', freezer: 'Freezer', pantry: 'Pantry' },
      addToShoppingAction: 'List',
      xpLabel: 'XP',
      goldLabel: 'Coin',
      levelLabel: 'Lv',
      todayLabel: 'Today',
      filters: { all: 'All', mine: 'Mine', open: 'Open', urgent: 'Urgent', done: 'Done' },
      tiers: { common: 'Easy', rare: 'Medium', epic: 'Hard', urgent: 'Urgent' },
      assignee: 'for',
      ornament: '·',
    },
  },

  // ----- CHARLYSSA -------------------------------------------------------
  dnd: {
    id: 'dnd',
    label: 'D&D',
    copy: {
      appName: 'The Keep',
      tasks: 'Quests',
      task: 'Quest',
      newTask: 'Inscribe Quest',
      completeTask: 'Mark Vanquished',
      completedToast: (xp, gold) => `⚔ Quest vanquished · +${xp} XP · +${gold} GP ⚔`,
      tasksSubtitle: 'deeds of valor await the bold',
      inventory: 'Provisions',
      inventorySubtitle: 'that which sustains the Keep',
      searchInventory: 'Seek thy provision…',
      depleted: 'Depleted',
      lowStock: 'Running low',
      recipes: 'Tomes',
      recipesSubtitle: 'recipes gathered through the ages',
      allIngredientsPresent: 'All components present',
      missingIngredients: (n) => `${n} component${n === 1 ? '' : 's'} missing`,
      notifications: 'Ravens',
      notificationsSubtitle: 'tidings from across the Keep',
      sendNotification: 'Dispatch Raven',
      shopping: 'Market',
      shoppingSubtitle: 'provisions yet to be gathered',
      addToShopping: 'Add to the list',
      shoppingEmpty: 'The marketkeeper awaits. No goods listed.',
      aiSuggest: 'Consult the Tome',
      aiSuggestSubtitle: 'the oracle reveals what may be cooked',
      aiThinking: 'The oracle ponders…',
      storage: { all: 'All Stores', fridge: 'The Coldhold', freezer: 'The Ice Vault', pantry: 'The Larder' },
      addToShoppingAction: 'To Market',
      xpLabel: 'XP',
      goldLabel: 'GP',
      levelLabel: 'Lv',
      todayLabel: 'Today',
      filters: { all: 'All', mine: 'Mine', open: 'Open', urgent: 'Urgent', done: 'Vanquished' },
      tiers: { common: 'Common', rare: 'Rare', epic: 'Epic', urgent: 'Urgent' },
      assignee: '◈',
      ornament: '❦',
    },
  },

  // ----- JAMIE -----------------------------------------------------------
  alien: {
    id: 'alien',
    label: 'Alien Girlie',
    copy: {
      appName: 'MOTHERSHIP',
      tasks: 'Directives',
      task: 'Directive',
      newTask: 'New Directive',
      completeTask: 'Transmit Complete',
      completedToast: (xp, gold) => `>> DIRECTIVE COMPLETE · +${xp} SIGNAL · +${gold} CREDITS <<`,
      tasksSubtitle: '// pending protocols from command',
      inventory: 'Kitchen',
      inventorySubtitle: '// supply hold inventory',
      searchInventory: 'scan supply hold…',
      depleted: 'DEPLETED',
      lowStock: 'LOW SUPPLY',
      recipes: 'Protocols',
      recipesSubtitle: '// nutritional synthesis routines',
      allIngredientsPresent: '>> ALL MATERIALS LOCATED',
      missingIngredients: (n) => `>> ${n} MATERIAL${n === 1 ? '' : 'S'} MISSING`,
      notifications: 'Transmissions',
      notificationsSubtitle: '// incoming signals from the crew',
      sendNotification: 'Transmit',
      shopping: 'Resupply',
      shoppingSubtitle: '// materials to acquire from planetside',
      addToShopping: 'Queue for resupply',
      shoppingEmpty: '>> SUPPLY MANIFEST EMPTY',
      aiSuggest: 'Run Synthesis',
      aiSuggestSubtitle: '// compute viable meal protocols',
      aiThinking: '// PROCESSING…',
      storage: { all: 'ALL BAYS', fridge: 'COLD BAY', freezer: 'CRYO BAY', pantry: 'DRY BAY' },
      addToShoppingAction: 'Queue',
      xpLabel: 'SIG',
      goldLabel: 'CRD',
      levelLabel: 'RANK',
      todayLabel: 'CYCLE',
      filters: { all: 'ALL', mine: 'MINE', open: 'ACTIVE', urgent: 'PRIORITY', done: 'ARCHIVE' },
      tiers: { common: 'ROUTINE', rare: 'ELEVATED', epic: 'CRITICAL', urgent: 'PRIORITY' },
      assignee: '►',
      ornament: '◉',
    },
  },

  // ----- JALEX -----------------------------------------------------------
  horror: {
    id: 'horror',
    label: 'Horror',
    copy: {
      appName: 'The Haunting',
      tasks: 'Rituals',
      task: 'Ritual',
      newTask: 'Inscribe Ritual',
      completeTask: 'Complete Ritual',
      completedToast: (xp, gold) => `† the ritual is complete · +${xp} dread · +${gold} coin †`,
      tasksSubtitle: 'what the house demands of us',
      inventory: 'The Larder',
      inventorySubtitle: 'what remains in the pantry',
      searchInventory: 'search the shelves…',
      depleted: 'Gone',
      lowStock: 'Dwindling',
      recipes: 'Grimoires',
      recipesSubtitle: 'recipes from the old cookbook',
      allIngredientsPresent: 'all is prepared',
      missingIngredients: (n) => `${n} thing${n === 1 ? '' : 's'} missing`,
      notifications: 'Whispers',
      notificationsSubtitle: 'what the walls have been saying',
      sendNotification: 'Whisper',
      shopping: 'The Errands',
      shoppingSubtitle: 'what the house still needs',
      addToShopping: 'Add to the list',
      shoppingEmpty: 'Nothing waiting. For now.',
      aiSuggest: 'Read the Grimoire',
      aiSuggestSubtitle: 'the book shows what the pantry allows',
      aiThinking: 'The grimoire turns its pages…',
      storage: { all: 'All', fridge: 'The Cold Room', freezer: 'The Deep Chill', pantry: 'The Cellar' },
      addToShoppingAction: 'Errand',
      xpLabel: 'Dread',
      goldLabel: 'Coin',
      levelLabel: 'Depth',
      todayLabel: 'Tonight',
      filters: { all: 'All', mine: 'Mine', open: 'Open', urgent: 'Cursed', done: 'Laid to Rest' },
      tiers: { common: 'Mundane', rare: 'Uneasy', epic: 'Grim', urgent: 'Cursed' },
      assignee: '†',
      ornament: '†',
    },
  },

  // ----- KELLY -----------------------------------------------------------
  marquee: {
    id: 'marquee',
    label: 'Marquee',
    copy: {
      appName: 'The Main Stage',
      tasks: 'Showstoppers',
      task: 'Showstopper',
      newTask: 'Add to Billing',
      completeTask: 'Take a Bow',
      completedToast: (xp, gold) => `✨ BRAVO! · +${xp} applause · +${gold} gold ✨`,
      tasksSubtitle: 'tonight\'s performance schedule',
      inventory: 'Green Room',
      inventorySubtitle: 'backstage provisions',
      searchInventory: 'search the dressing room…',
      depleted: 'Sold Out',
      lowStock: 'Last Call',
      recipes: 'Playbill',
      recipesSubtitle: 'featured numbers for dinner',
      allIngredientsPresent: 'The cast is ready — curtain up!',
      missingIngredients: (n) => `${n} understud${n === 1 ? 'y' : 'ies'} missing from the cast`,
      notifications: 'Callboard',
      notificationsSubtitle: 'notes from the stage manager',
      sendNotification: 'Post to Callboard',
      shopping: 'The Shopping Number',
      shoppingSubtitle: 'what the prop master needs',
      addToShopping: 'Add to the program',
      shoppingEmpty: 'The stage is bare — no props to fetch.',
      aiSuggest: 'Cue the Kitchen',
      aiSuggestSubtitle: 'tonight\'s menu, improvised from the pantry',
      aiThinking: 'The chef is warming up…',
      storage: { all: 'All Acts', fridge: 'Cold Storage', freezer: 'Deep Freeze', pantry: 'The Wings' },
      addToShoppingAction: 'Book it',
      xpLabel: 'Stars',
      goldLabel: 'Gold',
      levelLabel: 'Act',
      todayLabel: 'Tonight',
      filters: { all: 'All', mine: 'Mine', open: 'On Deck', urgent: 'Headliner', done: 'Encore' },
      tiers: { common: 'Opening Act', rare: 'Featured', epic: 'Headliner', urgent: 'Showstopper' },
      assignee: '★',
      ornament: '✦',
    },
  },

  // ----- JANIYA ----------------------------------------------------------
  cozy: {
    id: 'cozy',
    label: 'Cozy',
    copy: {
      appName: 'The Little House',
      tasks: 'Helpful Things',
      task: 'Helpful Thing',
      newTask: 'Add a Helpful Thing',
      completeTask: 'All Done!',
      completedToast: (xp, gold) => `🌻 Lovely work! · +${xp} stars · +${gold} honey pots`,
      tasksSubtitle: 'little things that help the house',
      inventory: 'Kitchen',
      inventorySubtitle: 'what we have in the cupboards',
      searchInventory: 'what are we looking for?',
      depleted: 'All gone',
      lowStock: 'Almost out',
      recipes: 'Cookbook',
      recipesSubtitle: 'warm things to make together',
      allIngredientsPresent: 'We have everything we need!',
      missingIngredients: (n) => `We need ${n} more thing${n === 1 ? '' : 's'}`,
      notifications: 'Notes',
      notificationsSubtitle: 'little notes for the house',
      sendNotification: 'Leave a Note',
      shopping: 'Shopping',
      shoppingSubtitle: 'things to fetch from the store',
      addToShopping: 'Add to the list',
      shoppingEmpty: 'The list is empty — all tucked in.',
      aiSuggest: 'What shall we make?',
      aiSuggestSubtitle: 'ideas from what we already have',
      aiThinking: 'Having a little think…',
      storage: { all: 'Everywhere', fridge: 'Icebox', freezer: 'Freezer', pantry: 'Cupboards' },
      addToShoppingAction: 'List it',
      xpLabel: 'Stars',
      goldLabel: 'Honey',
      levelLabel: 'Lv',
      todayLabel: 'Today',
      filters: { all: 'All', mine: 'Mine', open: 'To Do', urgent: 'Soon', done: 'Done!' },
      tiers: { common: 'Quick', rare: 'A bit', epic: 'Big one', urgent: 'Soon!' },
      assignee: 'for',
      ornament: '✿',
    },
  },

  space: {
    id: 'space',
    label: 'Cosmic',
    copy: {
      appName: 'The Observatory',
      tasks: 'Missions',
      task: 'Mission',
      newTask: 'Plot a Mission',
      completeTask: 'Log Complete',
      completedToast: (xp, gold) => `✦ Mission logged · +${xp} stardust · +${gold} quasars`,
      tasksSubtitle: 'charted courses awaiting execution',
      inventory: 'The Hold',
      inventorySubtitle: 'cargo manifest of the station',
      searchInventory: 'query the manifest…',
      depleted: 'Depleted',
      lowStock: 'Running low',
      recipes: 'Rations',
      recipesSubtitle: 'sustenance protocols',
      allIngredientsPresent: 'All rations available',
      missingIngredients: (n) => `Short ${n} ration${n === 1 ? '' : 's'}`,
      notifications: 'Signals',
      notificationsSubtitle: 'incoming from the deep dark',
      sendNotification: 'Broadcast',
      shopping: 'Supply Run',
      shoppingSubtitle: 'items to retrieve at next docking',
      addToShopping: 'Log for supply run',
      shoppingEmpty: 'Hold is stocked. All clear.',
      aiSuggest: 'Consult the Stars',
      aiSuggestSubtitle: 'the navigator charts a meal from the manifest',
      aiThinking: 'Plotting course…',
      storage: { all: 'All Decks', fridge: 'Cold Deck', freezer: 'Cryo Deck', pantry: 'Dry Stores' },
      addToShoppingAction: 'Log',
      xpLabel: 'Stardust',
      goldLabel: 'Quasars',
      levelLabel: 'Rank',
      todayLabel: 'Today',
      filters: { all: 'All', mine: 'Mine', open: 'Active', urgent: 'Priority', done: 'Logged' },
      tiers: { common: 'Routine', rare: 'Classified', epic: 'Mission Critical', urgent: 'Priority' },
      assignee: 'assigned to',
      ornament: '✦',
    },
  },

  oldwest: {
    id: 'oldwest',
    label: 'Old West',
    copy: {
      appName: 'The Homestead',
      tasks: 'Chores',
      task: 'Chore',
      newTask: 'Post a Chore',
      completeTask: 'Done and Dusted',
      completedToast: (xp, gold) => `★ Well done, partner · +${xp} grit · +${gold} bits`,
      tasksSubtitle: 'what needs doing round the ranch',
      inventory: 'The Larder',
      inventorySubtitle: 'what\'s laid up on the homestead',
      searchInventory: 'lookin\' for somethin\'?',
      depleted: 'Cleaned out',
      lowStock: 'Runnin\' low',
      recipes: 'Cookbook',
      recipesSubtitle: 'recipes from the old country',
      allIngredientsPresent: 'Got everything you need',
      missingIngredients: (n) => `Short ${n} fixin${n === 1 ? '' : 's'}`,
      notifications: 'Telegrams',
      notificationsSubtitle: 'word from around the homestead',
      sendNotification: 'Send Word',
      shopping: 'General Store',
      shoppingSubtitle: 'what to fetch from town',
      addToShopping: 'Put on the list',
      shoppingEmpty: 'Nothin\' needed from town.',
      aiSuggest: 'Ask the Cook',
      aiSuggestSubtitle: 'chuckwagon suggestions from what\'s on hand',
      aiThinking: 'Cook\'s thinkin\'…',
      storage: { all: 'All', fridge: 'Icehouse', freezer: 'Deep Freeze', pantry: 'The Larder' },
      addToShoppingAction: 'Add',
      xpLabel: 'Grit',
      goldLabel: 'Bits',
      levelLabel: 'Rank',
      todayLabel: 'Today',
      filters: { all: 'All', mine: 'Mine', open: 'To Do', urgent: 'Urgent', done: 'Done' },
      tiers: { common: 'Easy', rare: 'Tough', epic: 'Hard Day\'s Work', urgent: 'Right Now' },
      assignee: 'for',
      ornament: '✦',
    },
  },

  nineties: {
    id: 'nineties',
    label: '90s',
    copy: {
      appName: 'The Homepage',
      tasks: 'The List',
      task: 'Thing To Do',
      newTask: '+ ADD NEW !!',
      completeTask: 'DONE!',
      completedToast: (xp, gold) => `⭐ RAD!! · +${xp} cool points · +${gold} stickers ⭐`,
      tasksSubtitle: '<< updated daily!! >>',
      inventory: 'The Pantry',
      inventorySubtitle: 'whats in the kitchen!!',
      searchInventory: 'lookin for sumthin?',
      depleted: 'ALL GONE :(',
      lowStock: 'almost out!!',
      recipes: 'Recipe Book',
      recipesSubtitle: 'cool stuff to cook!!',
      allIngredientsPresent: 'YOU GOT EVERYTHING!!',
      missingIngredients: (n) => `need ${n} more thing${n === 1 ? '' : 's'}!!`,
      notifications: 'Guestbook',
      notificationsSubtitle: '<< new messages!! >>',
      sendNotification: 'SIGN IT',
      shopping: 'Shopping',
      shoppingSubtitle: 'stuff 2 grab at the store!!',
      addToShopping: 'ADD 2 CART!!',
      shoppingEmpty: '<< nothing here yet!! >>',
      aiSuggest: 'HELP ME COOK!!',
      aiSuggestSubtitle: 'gimme ideas from whats in the pantry!!',
      aiThinking: 'loading... please wait...',
      storage: { all: 'all', fridge: 'FRIDGE', freezer: 'FREEZER', pantry: 'PANTRY' },
      addToShoppingAction: '+ CART',
      xpLabel: 'Points',
      goldLabel: 'Stickers',
      levelLabel: 'Lvl',
      todayLabel: 'TODAY!!',
      filters: { all: 'all', mine: 'mine', open: 'to do', urgent: 'URGENT!!', done: 'done!' },
      tiers: { common: 'easy', rare: 'kinda tough', epic: 'BIG ONE!!', urgent: 'do it NOW!!' },
      assignee: '4',
      ornament: '★',
    },
  },

  underwater: {
    id: 'underwater',
    label: 'Reef',
    copy: {
      appName: 'The Reef',
      tasks: 'The Current',
      task: 'Current',
      newTask: 'Send a Current',
      completeTask: 'Let it drift',
      completedToast: (xp, gold) => `🐚 Gently done · +${xp} pearls · +${gold} seaglass`,
      tasksSubtitle: 'what the tide asks of us',
      inventory: 'The Shoals',
      inventorySubtitle: 'what we\'ve gathered from the reef',
      searchInventory: 'drift through the shoals…',
      depleted: 'Washed away',
      lowStock: 'Running shallow',
      recipes: 'The Kelp Book',
      recipesSubtitle: 'recipes passed down on the current',
      allIngredientsPresent: 'Everything is in the reef',
      missingIngredients: (n) => `Missing ${n} ingredient${n === 1 ? '' : 's'} from the reef`,
      notifications: 'Tides',
      notificationsSubtitle: 'news that drifts ashore',
      sendNotification: 'Send on the Tide',
      shopping: 'Surface',
      shoppingSubtitle: 'what we need to surface for',
      addToShopping: 'Add to the surface run',
      shoppingEmpty: 'The reef has everything it needs.',
      aiSuggest: 'Ask the Tides',
      aiSuggestSubtitle: 'what the current brings from the shoals',
      aiThinking: 'The tides are turning…',
      storage: { all: 'All Waters', fridge: 'The Cool', freezer: 'The Deep', pantry: 'The Dry Reef' },
      addToShoppingAction: 'Surface',
      xpLabel: 'Pearls',
      goldLabel: 'Seaglass',
      levelLabel: 'Depth',
      todayLabel: 'Today',
      filters: { all: 'All', mine: 'Mine', open: 'Drifting', urgent: 'Rising Tide', done: 'Settled' },
      tiers: { common: 'Gentle', rare: 'A current', epic: 'A deep swim', urgent: 'Rising tide' },
      assignee: 'for',
      ornament: '❀',
    },
  },

  station: {
    id: 'station',
    label: 'Bridge',
    copy: {
      appName: 'The Bridge',
      tasks: 'Away Missions',
      task: 'Away Mission',
      newTask: 'Log New Mission',
      completeTask: 'Mission Complete',
      completedToast: (xp, gold) => `⋆ Well done · +${xp} commendations · +${gold} credits`,
      tasksSubtitle: 'active orders from the Captain',
      inventory: 'Stores',
      inventorySubtitle: 'ship inventory from the quartermaster',
      searchInventory: 'query the database…',
      depleted: 'Depleted',
      lowStock: 'Reserves low',
      recipes: 'Replicator',
      recipesSubtitle: 'authorized meal patterns',
      allIngredientsPresent: 'All patterns available',
      missingIngredients: (n) => `Missing ${n} component${n === 1 ? '' : 's'}`,
      notifications: 'Comms',
      notificationsSubtitle: 'incoming from across the ship',
      sendNotification: 'Hail the Crew',
      shopping: 'Requisitions',
      shoppingSubtitle: 'supplies requested for next dock',
      addToShopping: 'File requisition',
      shoppingEmpty: 'No requisitions pending. Well done, crew.',
      aiSuggest: 'Consult the Computer',
      aiSuggestSubtitle: 'the ship\'s computer suggests meal patterns',
      aiThinking: 'Computing…',
      storage: { all: 'All Decks', fridge: 'Cold Storage', freezer: 'Cryostorage', pantry: 'Dry Stores' },
      addToShoppingAction: 'Requisition',
      xpLabel: 'Commendations',
      goldLabel: 'Credits',
      levelLabel: 'Rank',
      todayLabel: 'Today',
      filters: { all: 'All', mine: 'Mine', open: 'Active', urgent: 'Red Alert', done: 'Complete' },
      tiers: { common: 'Routine', rare: 'Priority', epic: 'Critical', urgent: 'Red Alert' },
      assignee: 'assigned to',
      ornament: '⋆',
    },
  },
};

export function getTheme(id: ThemeId | string | null | undefined) {
  if (!id) return THEMES.neutral;
  return THEMES[id as ThemeId] ?? THEMES.neutral;
}
